String dayName = 'Tuesday';
if(dayName == 'Thursday'){
    System.debug('Welcome out our sessions');
} else if(dayName.equals('Saturday) || dayName.equals('Sunday')) {
    System.debug('It is the weekend');
} else {
     System.debug('Sorry, no session today');
}

String fruitName1 = 'apple';
String fruitName2='Banana';

if(fruitName1.equals(fruitName2)) {
    System.debug('They are the same fruit');
} else {
    System.debug('They are different fruits');
}